<%@ Control Language="C#" AutoEventWireup="true" CodeFile="BrightIdeaForm.ascx.cs" Inherits="App_BI500_UserControl_BrightIdeaForm" %>

<%@ Register Src="~/UserControls/userFinder/Search4LocalUser.ascx" TagName="Search4LocalUser" TagPrefix="uc1" %>
<%@ Register Src="~/UserControls/dateControl.ascx" TagName="dateControl" TagPrefix="uc2" %>

<%@ Register Src="~/UserControls/userFinder/Search4User.ascx" TagName="Search4User" TagPrefix="uc3" %>
<%--<%@ Register Src="Search4LocalUser.ascx" TagName="Search4LocalUser" TagPrefix="uc3" %>--%>

<div class="container mt-3">

    <!-- Page Title -->
    <div class="card shadow-sm mb-3">
        <div class="card-header bg-success text-white fw-bold">
            Business Improvement Registration
        </div>
        <div class="card-body">
            <p>
                This is the Bright Ideas Project Registration form used to manage the storage, request
                and approval process for ideas generated by SCIN staff in the various areas of business.
                <br /><br />
                Thanks - Bright Idea Process Owners.
            </p>
        </div>
    </div>

    <div class="card shadow-sm mb-3">
        <div class="card-body">

            <div class="row mb-3">
                <label class="col-md-3 col-form-label fw-bold">Business Unit:
                    <asp:CompareValidator ID="CompareValidator3" runat="server"
                        ControlToValidate="drpBuzUnit"
                        ErrorMessage="Please select Business Unit"
                        Operator="NotEqual" Type="Integer" ValueToCompare="-1">*</asp:CompareValidator>
                </label>

                <div class="col-md-9">
                    <asp:DropDownList ID="drpBuzUnit" runat="server"
                        CssClass="form-select" Width="250px"
                        AutoPostBack="True" OnSelectedIndexChanged="drpBuzUnit_SelectedIndexChanged">
                    </asp:DropDownList>
                </div>
            </div>

            <div class="row mb-3">
                <label class="col-md-3 col-form-label fw-bold">Department:
                    <asp:CompareValidator ID="CompareValidator4" runat="server"
                        ControlToValidate="ddlDepartment"
                        ErrorMessage="Please select Business Unit Department"
                        Operator="NotEqual" Type="Integer" ValueToCompare="-1">*</asp:CompareValidator>
                </label>

                <div class="col-md-9">
                    <asp:DropDownList ID="ddlDepartment" runat="server"
                        CssClass="form-select" Width="250px"
                        AutoPostBack="True" OnSelectedIndexChanged="ddlDepartment_SelectedIndexChanged">
                    </asp:DropDownList>
                </div>
            </div>

            <div class="row">
                <label class="col-md-3 col-form-label fw-bold">Team:
                    <asp:CompareValidator ID="CompareValidator5" runat="server"
                        ControlToValidate="ddlTeam"
                        ErrorMessage="Please select Your Team"
                        Operator="NotEqual" Type="Integer" ValueToCompare="-1">*</asp:CompareValidator>
                </label>

                <div class="col-md-9">
                    <asp:DropDownList ID="ddlTeam" runat="server"
                        CssClass="form-select" Width="250px">
                    </asp:DropDownList>
                </div>
            </div>

        </div>
    </div>

    <div class="card shadow-sm mb-3">
        <div class="card-body">

            <div class="row mb-3">
                <label class="col-md-3 col-form-label fw-bold">
                    Project Improvement Title:
                    <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server"
                        ControlToValidate="txtProjectTitle"
                        ErrorMessage="Enter Project Improvement Title">*</asp:RequiredFieldValidator>
                </label>

                <div class="col-md-9">
                    <asp:TextBox ID="txtProjectTitle" runat="server"
                        CssClass="form-control" TextMode="MultiLine"
                        Height="50px"></asp:TextBox>
                </div>
            </div>

            <div class="row mb-3">
                <label class="col-md-3 col-form-label fw-bold">Project Champion:</label>
                <div class="col-md-9">
                    <uc1:Search4LocalUser ID="champion" runat="server" />
                    <em>(This is your immediate supervisor)</em>
                </div>
            </div>

            <div class="row mb-3">
                <label class="col-md-3 col-form-label fw-bold">Project Sponsor:</label>
                <div class="col-md-9">
                    <uc1:Search4LocalUser ID="Sponsor" runat="server" />
                    <em>(Supervisor to your immediate supervisor)</em>
                </div>
            </div>

            <div class="row">
                <label class="col-md-3 col-form-label fw-bold">Lean Team Support Focal Point:</label>
                <div class="col-md-9">
                    <uc1:Search4LocalUser ID="LeanFocalPoint" runat="server" />
                </div>
            </div>

        </div>
    </div>

    <div class="card shadow-sm mb-3">
        <div class="card-body">

            <div class="row mb-3">
                <label class="col-md-3 col-form-label fw-bold">
                    Business Case:
                    <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server"
                        ControlToValidate="txtBizCase"
                        ErrorMessage="Business Case is required">*</asp:RequiredFieldValidator>
                </label>
                <div class="col-md-9">
                    <asp:TextBox ID="txtBizCase" runat="server"
                        CssClass="form-control" TextMode="MultiLine"
                        Height="100px"></asp:TextBox>
                </div>
            </div>

            <div class="row">
                <label class="col-md-3 col-form-label fw-bold">
                    Opportunity Statement:
                    <asp:RequiredFieldValidator ID="RequiredFieldValidator3" runat="server"
                        ControlToValidate="txtOpportunityStmt"
                        ErrorMessage="Opportunity Statement is required">*</asp:RequiredFieldValidator>
                </label>
                <div class="col-md-9">
                    <asp:TextBox ID="txtOpportunityStmt" runat="server"
                        CssClass="form-control" TextMode="MultiLine"
                        Height="100px"></asp:TextBox>
                </div>
            </div>

        </div>
    </div>

    <div class="card shadow-sm mb-3">
        <div class="card-body">

            <div class="row mb-3">
                <label class="col-md-3 col-form-label fw-bold">
                    Expected Benefit/Impacted Area:
                    <asp:CompareValidator ID="CompareValidator2" runat="server"
                        ControlToValidate="drpBenefit"
                        ErrorMessage="Impacted Area is Required"
                        Operator="NotEqual" Type="Integer" ValueToCompare="-1">*</asp:CompareValidator>
                </label>

                <div class="col-md-9">
                    <asp:DropDownList ID="drpBenefit" runat="server"
                        CssClass="form-select" Width="250px"></asp:DropDownList>
                </div>
            </div>

            <div class="row mb-3">
                <label class="col-md-3 col-form-label fw-bold">Project Plan Completion Date:</label>
                <div class="col-md-9">
                    <uc2:dateControl ID="dtCompletion" runat="server" />
                </div>
            </div>

            <asp:HiddenField ID="HFRequestId" runat="server" />

            <div class="row">
                <div class="col-md-9 offset-md-3">
                    <asp:Button ID="btnDraft" runat="server" Text="Save as Draft"
                        CssClass="btn btn-secondary me-2" />

                    <asp:Button ID="btnSubmit" runat="server" Text="Submit"
                        CssClass="btn btn-success me-2"
                        OnClientClick="return confirm('Are you sure you want to send for approval?')" />

                    <asp:Button ID="btnClose" runat="server" Text="Close"
                        CssClass="btn btn-danger" />
                </div>
            </div>

        </div>
    </div>
</div>



<asp:ValidationSummary ID="ValidationSummary1" runat="server" ShowMessageBox="True" ShowSummary="False" />
